    EXE = myexe
    OBJS = TelemetryClient.o
    CPPFLAGS = -Iinclude
    SRCS=TelemetryClient.cpp BaseTelemetryContext.cpp TelemetryContextOther.cpp 
        
$(EXE): $(OBJS)
	g++ -o $@  $(OBJS)
        
depend: 
	makedepend -- $(CFLAGS) -- $(SRCS)
        
        


# DO NOT DELETE

TelemetryClient.o: TelemetryClient.h contracts/Contracts.h contracts/Domain.h
TelemetryClient.o: common/Common.h /usr/include/stdlib.h
TelemetryClient.o: /usr/include/features.h /usr/include/stdc-predef.h
TelemetryClient.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
TelemetryClient.o: /usr/include/gnu/stubs.h /usr/include/bits/waitflags.h
TelemetryClient.o: /usr/include/bits/waitstatus.h /usr/include/endian.h
TelemetryClient.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
TelemetryClient.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
TelemetryClient.o: /usr/include/bits/byteswap-16.h /usr/include/sys/types.h
TelemetryClient.o: /usr/include/time.h /usr/include/sys/select.h
TelemetryClient.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
TelemetryClient.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
TelemetryClient.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
TelemetryClient.o: /usr/include/bits/stdlib-float.h common/JsonWriter.h
TelemetryClient.o: common/Serializer.h common/Nullable.h contracts/Base.h
TelemetryClient.o: contracts/Data.h contracts/Envelope.h
TelemetryClient.o: contracts/DependencyKind.h contracts/SeverityLevel.h
TelemetryClient.o: contracts/CrashDataHeaders.h
TelemetryClient.o: contracts/CrashDataThreadFrame.h
TelemetryClient.o: contracts/CrashDataThread.h contracts/CrashDataBinary.h
TelemetryClient.o: contracts/CrashData.h contracts/DataPoint.h
TelemetryClient.o: contracts/DataPointType.h contracts/MetricData.h
TelemetryClient.o: contracts/RemoteDependencyData.h contracts/PageViewData.h
TelemetryClient.o: contracts/EventData.h contracts/DependencySourceType.h
TelemetryClient.o: contracts/RequestData.h contracts/StackFrame.h
TelemetryClient.o: contracts/ExceptionDetails.h contracts/ExceptionData.h
TelemetryClient.o: contracts/MessageData.h contracts/PageViewPerfData.h
TelemetryClient.o: contracts/Application.h contracts/Device.h
TelemetryClient.o: contracts/Location.h contracts/Operation.h
TelemetryClient.o: contracts/Session.h contracts/User.h contracts/Internal.h
TelemetryClient.o: contracts/SessionStateData.h contracts/SessionState.h
TelemetryClient.o: TelemetryClientConfig.h common/Common.h TelemetryContext.h
TelemetryClient.o: BaseTelemetryContext.h channel/TelemetryChannel.h
TelemetryClient.o: TelemetryClientConfig.h TelemetryContext.h
TelemetryClient.o: contracts/Contracts.h channel/utils/HttpRequest.h
TelemetryClient.o: channel/utils/HttpResponse.h common/Common.h
TelemetryClient.o: channel/utils/HttpHeaderFields.h
TelemetryClient.o: channel/utils/HttpHeaderField.h common/Utils.h
BaseTelemetryContext.o: BaseTelemetryContext.h TelemetryClientConfig.h
BaseTelemetryContext.o: common/Common.h contracts/Contracts.h
BaseTelemetryContext.o: contracts/Domain.h common/Common.h
BaseTelemetryContext.o: /usr/include/stdlib.h /usr/include/features.h
BaseTelemetryContext.o: /usr/include/stdc-predef.h /usr/include/sys/cdefs.h
BaseTelemetryContext.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
BaseTelemetryContext.o: /usr/include/bits/waitflags.h
BaseTelemetryContext.o: /usr/include/bits/waitstatus.h /usr/include/endian.h
BaseTelemetryContext.o: /usr/include/bits/endian.h
BaseTelemetryContext.o: /usr/include/bits/byteswap.h
BaseTelemetryContext.o: /usr/include/bits/types.h
BaseTelemetryContext.o: /usr/include/bits/typesizes.h
BaseTelemetryContext.o: /usr/include/bits/byteswap-16.h
BaseTelemetryContext.o: /usr/include/sys/types.h /usr/include/time.h
BaseTelemetryContext.o: /usr/include/sys/select.h /usr/include/bits/select.h
BaseTelemetryContext.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
BaseTelemetryContext.o: /usr/include/sys/sysmacros.h
BaseTelemetryContext.o: /usr/include/bits/pthreadtypes.h
BaseTelemetryContext.o: /usr/include/alloca.h
BaseTelemetryContext.o: /usr/include/bits/stdlib-float.h common/JsonWriter.h
BaseTelemetryContext.o: common/Serializer.h common/Nullable.h
BaseTelemetryContext.o: contracts/Base.h contracts/Data.h
BaseTelemetryContext.o: contracts/Envelope.h contracts/DependencyKind.h
BaseTelemetryContext.o: contracts/SeverityLevel.h
BaseTelemetryContext.o: contracts/CrashDataHeaders.h
BaseTelemetryContext.o: contracts/CrashDataThreadFrame.h
BaseTelemetryContext.o: contracts/CrashDataThread.h
BaseTelemetryContext.o: contracts/CrashDataBinary.h contracts/CrashData.h
BaseTelemetryContext.o: contracts/DataPoint.h contracts/DataPointType.h
BaseTelemetryContext.o: contracts/MetricData.h
BaseTelemetryContext.o: contracts/RemoteDependencyData.h
BaseTelemetryContext.o: contracts/PageViewData.h contracts/EventData.h
BaseTelemetryContext.o: contracts/DependencySourceType.h
BaseTelemetryContext.o: contracts/RequestData.h contracts/StackFrame.h
BaseTelemetryContext.o: contracts/ExceptionDetails.h
BaseTelemetryContext.o: contracts/ExceptionData.h contracts/MessageData.h
BaseTelemetryContext.o: contracts/PageViewPerfData.h contracts/Application.h
BaseTelemetryContext.o: contracts/Device.h contracts/Location.h
BaseTelemetryContext.o: contracts/Operation.h contracts/Session.h
BaseTelemetryContext.o: contracts/User.h contracts/Internal.h
BaseTelemetryContext.o: contracts/SessionStateData.h contracts/SessionState.h
BaseTelemetryContext.o: common/Utils.h
TelemetryContextOther.o: TelemetryContext.h BaseTelemetryContext.h
TelemetryContextOther.o: TelemetryClientConfig.h common/Common.h
TelemetryContextOther.o: contracts/Contracts.h contracts/Domain.h
TelemetryContextOther.o: common/Common.h /usr/include/stdlib.h
TelemetryContextOther.o: /usr/include/features.h /usr/include/stdc-predef.h
TelemetryContextOther.o: /usr/include/sys/cdefs.h
TelemetryContextOther.o: /usr/include/bits/wordsize.h
TelemetryContextOther.o: /usr/include/gnu/stubs.h
TelemetryContextOther.o: /usr/include/bits/waitflags.h
TelemetryContextOther.o: /usr/include/bits/waitstatus.h /usr/include/endian.h
TelemetryContextOther.o: /usr/include/bits/endian.h
TelemetryContextOther.o: /usr/include/bits/byteswap.h
TelemetryContextOther.o: /usr/include/bits/types.h
TelemetryContextOther.o: /usr/include/bits/typesizes.h
TelemetryContextOther.o: /usr/include/bits/byteswap-16.h
TelemetryContextOther.o: /usr/include/sys/types.h /usr/include/time.h
TelemetryContextOther.o: /usr/include/sys/select.h /usr/include/bits/select.h
TelemetryContextOther.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
TelemetryContextOther.o: /usr/include/sys/sysmacros.h
TelemetryContextOther.o: /usr/include/bits/pthreadtypes.h
TelemetryContextOther.o: /usr/include/alloca.h
TelemetryContextOther.o: /usr/include/bits/stdlib-float.h common/JsonWriter.h
TelemetryContextOther.o: common/Serializer.h common/Nullable.h
TelemetryContextOther.o: contracts/Base.h contracts/Data.h
TelemetryContextOther.o: contracts/Envelope.h contracts/DependencyKind.h
TelemetryContextOther.o: contracts/SeverityLevel.h
TelemetryContextOther.o: contracts/CrashDataHeaders.h
TelemetryContextOther.o: contracts/CrashDataThreadFrame.h
TelemetryContextOther.o: contracts/CrashDataThread.h
TelemetryContextOther.o: contracts/CrashDataBinary.h contracts/CrashData.h
TelemetryContextOther.o: contracts/DataPoint.h contracts/DataPointType.h
TelemetryContextOther.o: contracts/MetricData.h
TelemetryContextOther.o: contracts/RemoteDependencyData.h
TelemetryContextOther.o: contracts/PageViewData.h contracts/EventData.h
TelemetryContextOther.o: contracts/DependencySourceType.h
TelemetryContextOther.o: contracts/RequestData.h contracts/StackFrame.h
TelemetryContextOther.o: contracts/ExceptionDetails.h
TelemetryContextOther.o: contracts/ExceptionData.h contracts/MessageData.h
TelemetryContextOther.o: contracts/PageViewPerfData.h contracts/Application.h
TelemetryContextOther.o: contracts/Device.h contracts/Location.h
TelemetryContextOther.o: contracts/Operation.h contracts/Session.h
TelemetryContextOther.o: contracts/User.h contracts/Internal.h
TelemetryContextOther.o: contracts/SessionStateData.h
TelemetryContextOther.o: contracts/SessionState.h
